### ISSUE TITLE
how to execute a commands on the mysql container ?

### ISSUE THREAD

**Issue by wassimbj** [dokku/dokku-mysql#121]
the issue im facing is sql_mode issue, its says its not compatible with sql_mode=only_full_group_by

what i want to do is the same thing i did when im in local, what i did is run this command
```bash
mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
```

when the container starts 

full view

```yaml
mysql_db: 
      build: 
         context: ../
         dockerfile: ./docker/Dockerfile.dbs
      container_name: msql_db
      env_file: ../.env
      restart: always
      volumes: 
         - ../mysql-data:/var/lib/mysql
      command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
      ports: 
         - 3306:3306
```

that fixed my issue on localhost, i want to do the same. if i cant what do you suggest ?
cause ive tried connecting to mysql and running set sql_mode="" but it didnt work
